[project]
name = "ocr-id-parsing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "arabic-reshaper>=3.0.1",
    "dotenv>=0.9.9",
    "ipykernel>=7.3.0",
    "jiwer>=4.0.0",
    "jupyter>=1.1.1",
    "notebook>=7.6.0",
    "pandas>=3.0.3",
    "pillow>=12.3.0",
    "python-bidi>=0.6.11",
    "scikit-learn>=1.9.0",
    "torch>=2.10.0",
    "tqdm>=4.68.4",
    "transformers>=5.5.0",
    "ultralytics>=8.4.102",
    "unsloth>=2026.7.3",
    "wandb>=0.28.1",
    "weave>=0.53.2",
    "pyyaml>=6.0.2",
    "scipy>=1.18.0",
    "albumentations>=2.0.8",
    "opencv-python>=5.0.0.93",
    "onnxruntime>=1.27.0",
    "roboflow>=1.4.0",
    "fastapi[standard]>=0.139.2",
    "paddleocr>=3.7.0",
    "python-multipart>=0.0.32",
    "paddlepaddle>=3.3.1",
]
[tool.fastapi]
entrypoint = "src.inference.main:app"